repos:
  - repo: local
    hooks:
      - id: lockfile
        name: lockfile
        entry: uv lock --check
        language: system
        pass_filenames: false
        
      - id: lint
        name: lint
        entry: uv run ruff check 
        language: system
        types: [python]
        
      - id: format
        name: format
        entry: uv run ruff format --check
        language: system
        types: [python]
        
      - id: typecheck
        name: typecheck
        entry: uv run mypy
        language: system
        types: [python]
        
      - id: test
        name: test
        entry: uv run pytest --cov src/
        language: system
        pass_filenames: false