[project]
name = "fastapi-template"
description = "FastAPI template"
# version is not maintained. the real version comes from the git tag,
# which is set by semantic-release, see .releaserc.
version = "1.0.0"
requires-python = ">=3.13"

dependencies = [
    "fastapi>=0.118.0",
    "pydantic-settings>=2.11.0",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "fastapi[standard]>=0.118.0",
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.13.2",
    "uv-build>=0.8.22",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

# tools

[tool.ruff]
src = ["src/", "test/"]
line-length = 120

[tool.mypy]
mypy_path = ["src"]
files = ["src", "test"]
strict = true

[tool.pytest.ini_options]
pythonpath = ["src/"]

[tool.coverage.run]
parallel = true
omit = ["*/__init__.py"]
